######################################################################
# Automatically generated by qmake (3.0) Fri May 30 12:48:26 2014
######################################################################

TEMPLATE = app
TARGET = QINT2
INCLUDEPATH += .

# Input
HEADERS +=
SOURCES += main.cpp
